/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppMain: typeof import('./src/layouts/components/AppMain/index.vue')['default']
    Avatar: typeof import('./src/components/Avatar/index.vue')['default']
    Breadcrumb: typeof import('./src/layouts/components/Breadcrumb/index.vue')['default']
    Dashboard: typeof import('./src/views/dashboard/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layouts: typeof import('./src/layouts/index.vue')['default']
    Navbar: typeof import('./src/layouts/components/Navbar/index.vue')['default']
    RightPanel: typeof import('./src/layouts/components/RightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/index.vue')['default']
    Settings: typeof import('./src/layouts/components/Settings/index.vue')['default']
    Sidebar: typeof import('./src/layouts/components/Sidebar/index.vue')['default']
    SidebarExt: typeof import('./src/layouts/components/Sidebar/SidebarItemLink.vue')['default']
    SidebarItem: typeof import('./src/layouts/components/Sidebar/SidebarItem.vue')['default']
    SidebarItemLink: typeof import('./src/layouts/components/Sidebar/SidebarItemLink.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./src/layouts/components/TagsView/index.vue')['default']
    ThemePicker: typeof import('./src/layouts/components/ThemePicker/index.vue')['default']
  }
}
